### ISSUE TITLE
deleted message bug

### ISSUE THREAD

**Issue by titustitus98** [iBlitzkriegi/Vixio#142]
so i have made a code where when a message in discord gets deleted it gets sent in an embed in another channel, however this does not happen, when a message does get deleted it sends an embed in the defined channel saying that the bot deleted a message and says <none> instead of the message.

**Comment by GamingGeek** [comment]
This is not a bug. Blitz hasn't implemented any message caching in Vixio (I'm guessing due to performance issues) so it's not possible to do while keeping the server stable. I have done it before but my server kept crashing and had to remove it. Maybe this could turn into a feature request for message caching but I highly doubt Blitz will do that...

**Comment by GamingGeek** [comment]
@Snow-Pyon I tried to do it before but it only worked if I saved messages in a variable. Else it would just give <none>. I had heard JDA caches a lot but  I thought that maybe Blitz had somehow stopped it for potential performance increases as it wasn't working. I've tried many different hosts and even localhost but `on message deleted` never worked

**Comment by Pikachu920** [comment]
@snow-pyon JDA caches a lot of stuff definitely but messages do not get cached

**Comment by iBlitzkriegi** [comment]
Vixio does in a way actually cache messages, if the message was sent while the bot was alive then Vixio's UpdatingMessage will keep track of the attributes of the message. This is the full extent Vixio will go with caching messages for you.
